services:
  app:
    build:
      context: .
      args:
        RAILS_ENV: development
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    environment:
      RAILS_ENV: development
    command: >
      sh -c "rm -f tmp/pids/server.pid && bundle exec rails server -b 0.0.0.0 -p 3000"
    stdin_open: true
    tty: true
    depends_on:
      - db
  db:
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - pg_data:/var/lib/postgresql/data
volumes:
  pg_data:
