default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: db
  username: postgres
  password: password

development:
  <<: *default
  database: quick_services_development

test:
  <<: *default
  database: quick_services_test

production:
  primary: &primary_production
    <<: *default
    database: quick_services_production
    username: app
    password: <%= ENV["APP_DATABASE_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: quick_services__production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: quick_services__production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: quick_services__production_cable
    migrations_paths: db/cable_migrate
